In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


/opt/homebrew/anaconda3/envs/pyt1-osx-64/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
from training_new import get_data_loaders, train

In [ ]:
from model import Model

In [ ]:
model = Model(3, 16, 21, 2, 0.5)

In [ ]:
train(model, "./solver/sol_examples/vrp20/sols.pkl", epochs=10, batch_size=128)

In [6]:
train(model, "./solver/sol_examples/vrp20/sols.pkl", epochs=3, max_instances=200)

Parsing Graphs:   0%|                                                                                                                                                                      | 0/200 [00:00<?, ?it/s]/Users/roberto/Desktop/stanford/cs224w/project/cs224w/graph.py:133: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666646991213/work/aten/src/ATen/native/TensorShape.cpp:3281.)
  edge_list = torch.LongTensor(edge_list).T
Epochs:   0%|                                                                                                                                                                                | 0/3 [00:00<?, ?it/s]

Train 0 - loss:2.3112, acc:0.2500
Valid 0 - loss:2.7209, acc:0.1689
Train 0 - loss:2.7004, acc:0.0625
Valid 0 - loss:2.6189, acc:0.1656
Train 0 - loss:2.2235, acc:0.1875
Valid 0 - loss:2.5477, acc:0.1667
Train 0 - loss:2.1605, acc:0.1250
Valid 0 - loss:2.4968, acc:0.1700
Train 0 - loss:2.4575, acc:0.1875
Valid 0 - loss:2.4569, acc:0.1787
Train 0 - loss:2.0319, acc:0.1875
Valid 0 - loss:2.4292, acc:0.1798
Train 0 - loss:2.4600, acc:0.1875
Valid 0 - loss:2.4074, acc:0.1787
Train 0 - loss:2.5739, acc:0.0625
Valid 0 - loss:2.3930, acc:0.1831
Train 0 - loss:2.2395, acc:0.1250
Valid 0 - loss:2.3791, acc:0.1842
Train 0 - loss:2.5316, acc:0.1250
Valid 0 - loss:2.3691, acc:0.1831
Train 0 - loss:2.6110, acc:0.0625
Valid 0 - loss:2.3618, acc:0.1842
Train 0 - loss:2.2735, acc:0.1875
Valid 0 - loss:2.3557, acc:0.1820
Train 0 - loss:2.1430, acc:0.0625
Valid 0 - loss:2.3504, acc:0.1787
Train 0 - loss:2.3570, acc:0.1875
Valid 0 - loss:2.3475, acc:0.1743
Train 0 - loss:2.2665, acc:0.1875
Valid 0 - loss

Epochs:   0%|                                                                                                                                                                                | 0/3 [00:03<?, ?it/s]


KeyboardInterrupt: 

In [7]:
train_dl, _ = get_data_loaders("./solver/sol_examples/vrp20/sols.pkl")

 ... (more hidden) ...


In [8]:
len(train_dl)

229

In [10]:
batches = list(train_dl)

In [17]:
type(batches[0].x)

list

In [18]:
import sys

from torch.optim import Adam
from tqdm import tqdm
import torch
from torch import nn
import itertools
import pandas as pd

from model import Model
from generator import *

from torch_geometric.loader import DataLoader
from typing import List
from util import *

In [19]:
from training_new import get_solution_instances

In [20]:
graphs_path = "./solver/sol_examples/vrp20/sols.pkl"

In [21]:
graphs = []
sol_instances = get_solution_instances(graphs_path)
split_idx = int(0.8 * len(sol_instances))

In [22]:
sol_instances[0].get_all_graphs()[0]

In [23]:

"""Given the path to the pickle of graphs generated and further solved
using LKH, returns 2 PYG's DataLoaders, one for training and the other
for validation.
"""

for sol_instance in tqdm(sol_instances, "Parsing Graphs"):
    ## need to specify how many partial solutions we need partial solution index
    #cvrp_graphs = sol_instance.get_partial_solutions()
    cvrp_graphs = sol_instance.get_all_graphs()
    # convert to pytorch geometric dataset
    cvrp_graphs = list(map(lambda g: g.export_pyg(), cvrp_graphs))
    
    graphs.append(cvrp_graphs)

# train_graphs = itertools.chain.from_iterable(graphs[:split_idx])
# valid_graphs = itertools.chain.from_iterable(graphs[split_idx:])

# train_graphs = DataLoader(list(train_graphs), shuffle=True, batch_size=batch_size)
# valid_graphs = DataLoader(list(valid_graphs), shuffle=True, batch_size=batch_size)

 ... (more hidden) ...


In [24]:
sample_graphs = list(cvrp_graphs)

In [29]:
train_graphs = DataLoader(sample_graphs[:3], shuffle=False, batch_size=2)

In [32]:
train_graphs = list(train_graphs)

In [42]:
train_graphs[0].x

[array([[0.48795906, 0.38488354, 0.        ],
        [0.65106481, 0.29048421, 1.        ],
        [0.52603219, 0.97074277, 2.        ],
        [0.01844732, 0.87313311, 6.        ],
        [0.59595635, 0.7511838 , 1.        ],
        [0.19020065, 0.6894146 , 5.        ],
        [0.53635501, 0.06441764, 4.        ],
        [0.28682576, 0.85332603, 8.        ],
        [0.44858972, 0.10795248, 3.        ],
        [0.39920675, 0.23034469, 3.        ],
        [0.82212058, 0.26980682, 6.        ],
        [0.39057818, 0.27630326, 5.        ],
        [0.11934537, 0.60380564, 6.        ],
        [0.4338518 , 0.07372146, 1.        ],
        [0.7565152 , 0.05686733, 8.        ],
        [0.83810693, 0.7011449 , 6.        ],
        [0.06043427, 0.29609497, 7.        ],
        [0.07082987, 0.8987102 , 4.        ],
        [0.96253617, 0.31843071, 8.        ],
        [0.11436427, 0.16957051, 5.        ],
        [0.22810337, 0.61112956, 1.        ]]),
 array([[0.48795906, 0.38488354,

In [40]:
sample_graphs[1].x

array([[0.48795906, 0.38488354, 0.        ],
       [0.65106481, 0.29048421, 1.        ],
       [0.52603219, 0.97074277, 2.        ],
       [0.01844732, 0.87313311, 6.        ],
       [0.59595635, 0.7511838 , 1.        ],
       [0.19020065, 0.6894146 , 5.        ],
       [0.53635501, 0.06441764, 4.        ],
       [0.28682576, 0.85332603, 8.        ],
       [0.44858972, 0.10795248, 3.        ],
       [0.39920675, 0.23034469, 3.        ],
       [0.82212058, 0.26980682, 6.        ],
       [0.39057818, 0.27630326, 5.        ],
       [0.11934537, 0.60380564, 6.        ],
       [0.4338518 , 0.07372146, 1.        ],
       [0.7565152 , 0.05686733, 8.        ],
       [0.83810693, 0.7011449 , 6.        ],
       [0.06043427, 0.29609497, 7.        ],
       [0.07082987, 0.8987102 , 4.        ],
       [0.96253617, 0.31843071, 8.        ],
       [0.11436427, 0.16957051, 5.        ],
       [0.22810337, 0.61112956, 1.        ]])

In [35]:
len(train_graphs[0].x)

2

SyntaxError: incomplete input (3515030944.py, line 1)

In [220]:
for batch_graph in train_graphs:
    pass

In [11]:
import pdb; pdb.set_trace()

--Call--
> /opt/homebrew/anaconda3/envs/pyt1-osx-64/lib/python3.10/site-packages/IPython/core/displayhook.py(258)__call__()
    256         sys.stdout.flush()
    257 
--> 258     def __call__(self, result=None):
    259         """Printing with history cache management.
    260 



ipdb>  b
ipdb>  exit()


In [3]:
dls = get_data_loaders("./solver/sol_examples/vrp20/sols.pkl")

Parsing Graphs: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:15<00:00, 262.38it/s]


In [4]:
train, valid = dls

In [5]:
train

In [17]:
'a'

'a'

In [2]:
import pandas as pd

In [3]:
sols = pd.read_pickle("./solver/sol_examples/vrp20/sols.pkl")

In [5]:
len(sols)

4000

In [7]:
len(sols[0])

2

In [8]:
sols[0][0]

[[0.3189664036607044, 0.9472218293925415],
 [[0.9187083622644343, 0.8138443779202849],
  [0.03407709152060179, 0.9433728691449649],
  [0.9504391649155011, 0.8065910506231764],
  [0.4812780422030105, 0.9667592260965735],
  [0.41697908439698783, 0.3188401259211743],
  [0.01644281760441979, 0.03818192568347378],
  [0.05308965044499003, 0.1279608146375314],
  [0.033383159457254785, 0.226421092399535],
  [0.5439089053152613, 0.17862580998720157],
  [0.17934478386603347, 0.14961321573593056],
  [0.6830131255680931, 0.46900855062027413],
  [0.7682479309034291, 0.6688140585670866],
  [0.4412681772565863, 0.5952254504410683],
  [0.4616566187671286, 0.9632668729744531],
  [0.14781137906345743, 0.9068131269665934],
  [0.4979248360998828, 0.5924984671923367],
  [0.684657987906487, 0.17745066401182163],
  [0.8646854870467618, 0.4820887768136817],
  [0.06934179411604258, 0.36473133604507435],
  [0.36150419332229866, 0.47206349952741467]],
 [5, 5, 3, 6, 9, 6, 1, 8, 7, 3, 2, 1, 7, 1, 3, 5, 3, 5, 3, 1]

In [9]:
sols[0][1]

(5.9274792484481775,
 [10, 6, 7, 8, 19, 2, 15, 0, 14, 4, 1, 3, 12, 16, 13, 0, 20, 5, 9, 17, 18, 11])

In [10]:
set([1, 2, 3, 1])

{1, 2, 3}

In [12]:
x = torch.tensor([[1, 2, 3.0]])

In [13]:
x.shape

torch.Size([1, 3])

In [16]:
x.squeeze().argmax().cpu().item()

2

In [1]:
import torch

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


/opt/homebrew/anaconda3/envs/pyt1-osx-64/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import time

import networkx as nx
import numpy as np
import torch
import pandas as pd

from torch_geometric.datasets import TUDataset
from torch_geometric.datasets import Planetoid
from torch_geometric.data import DataLoader

import torch_geometric.nn as pyg_nn

import matplotlib.pyplot as plt

In [3]:
from torch_geometric.datasets import TUDataset

# if 'IS_GRADESCOPE_ENV' not in os.environ:
root = './tmp/enzymes'
name = 'ENZYMES'

# The ENZYMES dataset
pyg_dataset= TUDataset(root, name)

In [4]:
dataset = pyg_dataset

In [5]:
data_loader = DataLoader(dataset, batch_size=3)

/opt/homebrew/anaconda3/envs/pyt1-osx-64/lib/python3.10/site-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [6]:
a = next(iter(data_loader))

In [9]:
dataset_list = [dataset[i] for i in range(len(dataset))]

In [10]:
from torch_geometric.loader import DataListLoader

In [19]:
list_dl = DataListLoader(dataset_list, batch_size=3)

In [26]:
next(iter(DataLoader(dataset_list, batch_size=3)))

DataBatch(edge_index=[2, 362], x=[85, 3], y=[3], batch=[85], ptr=[4])

In [20]:
next(iter(list_dl))

[Data(edge_index=[2, 168], x=[37, 3], y=[1]),
 Data(edge_index=[2, 102], x=[23, 3], y=[1]),
 Data(edge_index=[2, 92], x=[25, 3], y=[1])]

In [53]:
type(a)

torch_geometric.data.batch.DataBatch

In [54]:
from torch_geometric.data.batch import DataBatch

In [56]:
type(data_loader)

torch_geometric.deprecation.DataLoader

In [57]:
type(dataset)

torch_geometric.datasets.tu_dataset.TUDataset

In [55]:
type(a) 

True

In [28]:
a = (data_loader)

TypeError: 'DataLoader' object is not an iterator

Data(edge_index=[2, 92], x=[25, 3], y=[1])

In [12]:
TUDataset

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])